import { Outfit, Cinzel } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';
import Footer from './_components/Footer';
import Rating from './_components/Rating';

const outfit = Outfit({ subsets: ['latin'] });
const cinzel = Cinzel({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="md:px-20">
          <Header />
          {children}
          <Rating/>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
